

# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
    message: /updated readme.*|update readme.*s/

# Don't use a build system, our test_script does that
build: false

# Kick off the CI/CD pipeline
test_script:
    - ps: . ./build.ps1
